version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: example,test,test_dropwizard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d